import React, { useRef } from "react";
import { Code, Download, FileCode, FileJson, FileText, Sparkles, Upload } from "lucide-react";
import { ContextPackage, Conversation } from "../../shared/types";
import { CodeAggregator } from "../../context-engine/code-aggregator";

interface ExportImportModalProps {
  contextPackage?: ContextPackage;
  rawConversation?: Conversation | null;
  onImportAICP: (importedData: any) => void;
}

export const ExportImportModal: React.FC<ExportImportModalProps> = ({
  contextPackage,
  rawConversation,
  onImportAICP
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const codeAggregator = new CodeAggregator();

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJSON = () => {
    if (!contextPackage) return;
    const jsonStr = JSON.stringify(contextPackage, null, 2);
    downloadFile(jsonStr, `${contextPackage.title.replace(/\s+/g, "_")}_context.json`, "application/json");
  };

  const handleExportMarkdown = () => {
    if (!contextPackage) return;
    downloadFile(contextPackage.formattedMarkdown, `${contextPackage.title.replace(/\s+/g, "_")}_context.md`, "text/markdown");
  };

  const handleExportCursorRules = () => {
    if (!contextPackage) return;
    const meta = contextPackage.metadata;
    const rulesText = `# Project Context Rules (Generated by ContextBridge v2.0)

## Tech Stack & Frameworks
${meta.technologies?.map((t) => `- ${t}`).join("\n") || "- Not specified"}

## Architectural Decisions
${meta.decisions?.map((d) => `- ${d}`).join("\n") || "- Follow standard architectural best practices"}

## Open Tasks & Goals
${meta.openTasks?.map((t) => `- [ ] ${t}`).join("\n") || "- Execute core requirements"}

## Code Guidelines
- Maintain 100% type safety and clean modular structure.
- Auto-redact sensitive secrets and connection strings before deployment.
`;

    downloadFile(rulesText, ".cursorrules", "text/plain");
  };

  const handleExportObsidian = () => {
    if (!contextPackage) return;
    const meta = contextPackage.metadata;
    const yamlObsidian = `---
title: "${contextPackage.title}"
date: ${new Date().toISOString().split("T")[0]}
source: ${contextPackage.sourceProvider}
tags:
  - context-bridge
  - ai-transcripts
  - architecture
---

# ${contextPackage.title}

> **Source Platform**: ${contextPackage.sourceProvider.toUpperCase()} | **Fidelity**: ${contextPackage.informationRetentionPercentage}%

## Primary Goal
${meta.goal || "Not specified"}

## Architectural Decisions
${meta.decisions?.map((d) => `- ${d}`).join("\n") || "- None logged"}

## Tech Stack
${meta.technologies?.map((t) => `- \`${t}\``).join(", ") || "- N/A"}

---
${contextPackage.formattedMarkdown}
`;

    downloadFile(yamlObsidian, `${contextPackage.title.replace(/\s+/g, "_")}_obsidian.md`, "text/markdown");
  };

  const handleExportCodeSpecs = () => {
    if (!rawConversation) return;
    const aggResult = codeAggregator.aggregate(rawConversation);
    const filename = `${(rawConversation.title || "architecture").replace(/\s+/g, "_")}_code_specs.md`;
    downloadFile(aggResult.formattedMarkdown, filename, "text/markdown");
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        onImportAICP(parsed);
      } catch (err) {
        alert("Invalid AICP JSON package file.");
      }
    };
    reader.readAsText(file);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
      {/* IDE Rules Exporter */}
      <div className="panel-card" style={{ borderLeft: "4px solid var(--primary)" }}>
        <div className="panel-header">
          <span className="panel-title" style={{ display: "flex", alignItems: "center", gap: "6px" }}>
            <Sparkles size={13} color="var(--primary)" /> IDE Rules & PKM Vault Exporters
          </span>
          <span style={{ fontSize: "10px", fontWeight: 700, color: "var(--primary)" }}>v2.0 Superpowers</span>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginTop: "4px" }}>
          <button className="btn-secondary" onClick={handleExportCursorRules} disabled={!contextPackage}>
            <FileCode size={14} color="var(--primary)" /> Generate .cursorrules
          </button>
          <button className="btn-secondary" onClick={handleExportObsidian} disabled={!contextPackage}>
            <FileText size={14} color="var(--success)" /> Obsidian Vault (.md)
          </button>
        </div>
      </div>

      {/* Code Specs Aggregator */}
      <div className="panel-card">
        <span className="panel-title">Code Specs & Architecture Aggregator</span>
        <button
          className="btn-secondary"
          onClick={handleExportCodeSpecs}
          disabled={!rawConversation}
          style={{ marginTop: "4px", width: "100%", background: "var(--primary-light)", color: "var(--primary)", border: "1px solid var(--primary)" }}
        >
          <Code size={14} /> Download Aggregated Code Specs (architecture_specs.md)
        </button>
      </div>

      {/* AICP Package Exporter */}
      <div className="panel-card">
        <span className="panel-title">Universal AICP Package Formats</span>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginTop: "4px" }}>
          <button className="btn-secondary" onClick={handleExportJSON} disabled={!contextPackage}>
            <FileJson size={14} /> AICP (.json)
          </button>
          <button className="btn-secondary" onClick={handleExportMarkdown} disabled={!contextPackage}>
            <Download size={14} /> Clean Markdown (.md)
          </button>
        </div>
      </div>

      {/* Import Package */}
      <div className="panel-card">
        <span className="panel-title">Import & Restore Context Vault</span>
        <input
          type="file"
          accept=".json"
          ref={fileInputRef}
          style={{ display: "none" }}
          onChange={handleFileUpload}
        />
        <button
          className="btn-secondary"
          onClick={() => fileInputRef.current?.click()}
          style={{ marginTop: "4px" }}
        >
          <Upload size={14} /> Restore Context from AICP .json File
        </button>
      </div>
    </div>
  );
};
